export { default as SectionAccount } from './SectionAccount'
export { default as SectionBankDetails } from './SectionBankDetails'
export { default as SectionNotifications } from './SectionNotifications'
export { default as SectionPassword } from './SectionPassword'
export { default as SectionProfile } from './SectionProfile'